### ISSUE TITLE
Tesseract crashed: Failed loading language 'eng'

### ISSUE THREAD

**Issue by talalt** [evermeer/PassportScanner#12]
Hi! When I try to use PassportScanner he crashes with that error:

Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
fatal error: unexpectedly found nil while unwrapping an Optional value

How can I fix that? Thanks!

**Comment by harryblam** [comment]
hey @talalt did you fix this? If so, how? Thanks

**Comment by evermeer** [comment]
you need a testdata folder in the root of your app which includes a language file.

**Comment by harryblam** [comment]
Ah! Yes I see that in your instructions also now. Thanks for pointing that out.
