### ISSUE TITLE
Camera freeze in white screen

### ISSUE THREAD

**Issue by punto2018** [evermeer/PassportScanner#21]
The issue can be reproduced as follow:
- start the ocr by pressing "scan" in the demo
- the camera view show "some frame" for a while
- than it "fade" in white nothing can be done to acquire the MRZ

Tested on iPhone 6S and iOS 12.

![img_0061trim](https://user-images.githubusercontent.com/32935246/46807635-aac40280-cd6a-11e8-9878-3e28588e56c8.gif)

**Comment by evermeer** [comment]
There is an auto brightness adjustment. I thought this had an upper and lower limit. It looks like ik goes to infinite. Do you have the same result when you start scan and the camera is already pointed to a document?

**Comment by evermeer** [comment]
Now fixe after PR merge and publish as version 4.0.0
