### ISSUE TITLE
'Camera' cannot be constructed because it has no accessible initializers

### ISSUE THREAD

**Issue by mrhaxic** [evermeer/PassportScanner#32]
Building on Swift 4 and get the below error

`'Camera' cannot be constructed because it has no accessible initializers`

**Comment by evermeer** [comment]
The demo app is build against Swift 4.2? Is that also the version you are using?

Do you get the error on this line?
            camera = try Camera(sessionPreset: AVCaptureSession.Preset.hd1920x1080)
I do remember that the AVCaptureSession enum was changed somewhere in version 4.

**Comment by mrhaxic** [comment]
Actually, the app is running on Swift 4.0 but I already used pods on Swift 4.2 and I didn't face that issue. Yes I got an error on the below line

`camera = try Camera(sessionPreset: AVCaptureSession.Preset.hd1920x1080)`

**Comment by evermeer** [comment]
What is the PassportScanner version that you use? It should be 4.4.0.
If I change the demo app to Swift 4, then it still compiles

**Comment by mrhaxic** [comment]
I will try and get back to you

**Comment by evermeer** [comment]
Did you solve this issue?
