### ISSUE TITLE
Possible memory leak or normal behavior

### ISSUE THREAD

**Issue by babucha** [evermeer/PassportScanner#35]
I've just noticed that after each scan the memory allocated is getting 8-10Mb bigger (after about 10 scans memory usage exceeds 100 Mb ). Is it OK, or maybe an issue of Debug Navigator? It seems that when the PassportScannerController dismisses, it has not been fully deallocated. Tesseract cash clean up doesn't help.

**Comment by babucha** [comment]
Probably, I've found a solution (taken the problem really exists) - added  a check if the var tesseract has already been assigned to `@objc public func setup()`. Now memory usage remains stable even after a multiple consecutive scans

**Comment by evermeer** [comment]
Sounds good. Could you make a Pull Request for that?

**Comment by evermeer** [comment]
The change is published as version 4.6.0
