### ISSUE TITLE
Swift 5 - It doesn't compile

### ISSUE THREAD

**Issue by mjurfest** [evermeer/PassportScanner#39]
I am using Swift 5 and when trying to run the sample code on my project, it doesn't compile.

Errors: 

<img width="995" alt="Screen Shot 2019-12-17 at 16 41 05" src="https://user-images.githubusercontent.com/17320967/71005426-534ac080-20ec-11ea-8c72-134daaaad629.png">

@evermeer any idea why this is happening?

**Comment by evermeer** [comment]
The current version of the project was for Swift 4.2. I just made some changes to make it Swift 5 compatible. It's already pushed to GitHub. I will publish the cocoapod now.

**Comment by mjurfest** [comment]
It compiles now for Swift 5. Just a recommendation: update the README since it shows the old code and it has some compiling errors.
