### ISSUE TITLE
Add support to scan the MRZ of an ID card

### ISSUE THREAD

**Issue by evermeer** [evermeer/PassportScanner#5]
As reported by @jrodriguezq there is no support for the MRZ for an ID card. I will add this as an enhanecment later.

Original question:

The last commit fixes the issue that I had with the camera, now it looks like this:
![img_3139](https://cloud.githubusercontent.com/assets/7376923/17492297/2b7d1704-5d79-11e6-9b9f-78a15208b380.PNG)

The OCR it's working, but I'm not able to correctly read the MRZ. As you can see, the image appears to be clear enough.
The usual case of the mrz captured it's something like this:

INCHL1D41230409D26<<<<<<<<<<<<
9002063M2002064CHL17409866<2<6
CORTES<CONTRERAS<<SERGIO<JAV ll 12

This appears to be almost correct, but some numbers and blank characters usually stand in the way and I'm not able to scan the MRZ.
Is there any configuration that I'm missing? 

Again, many thanks for the library.

**Comment by sahar12345** [comment]
Hi can I talk to u about the programe

**Comment by evermeer** [comment]
@sahar12345 sure

**Comment by sahar12345** [comment]
I want to make programe in phone app like netbeans and xamrine must make iOS and android separate and I want connect to server can u the programe read I don't understand good to the folder code u put and how communicate with server that make confused

**Comment by sahar12345** [comment]
Netbeans in java programe

**Comment by sahar12345** [comment]
If that reading for national I'd card like Japan or negirea national card like this programe of passport

**Comment by sahar12345** [comment]
And so thank you so much

**Comment by evermeer** [comment]
Passport scanner is a complete native iOS only solution. There is no support for Android. There is no server required. The OCR is done on the phone itself. 

If you want to make an iOS app that sends the result of a scan to your own server, then you have to create your own logic for that. In the demo app you will have the file ViewController.swift which calls the PassportScanner interface. There in the function processMRZ you can add logic for handling the MRZ information.

**Comment by sahar12345** [comment]
Thank you but in my opinion that netbeans can make programe to all kinds iOS and android and its supported,that idea of logic server I will make today and show you and am glad if reply on results that from ur kind,thnx to u.

**Comment by punto2018** [comment]
Any news for this topic? 
Currently I'm working with 3 lines passports so I'm starting to develop the validator.
I can't find technical infos (checksum, char position semantic, etc) in order to integrate the support.

**Comment by evermeer** [comment]
@punto2018 
For the password MRZ I was able to create the logic based on what was described on wikipedia. See https://en.wikipedia.org/wiki/Machine-readable_passport as you can see there is also a description for official travel documents with 3 lines. That should be enough information.

**Comment by punto2018** [comment]
Good news, resolving the camera issues it seem that the parsing is working fine. If you agree I can share my changes and generate a pull request. The idea is to add a property in order to easily switch MRZ parsing type (2 lines or 3 lines), using the 2 lines as default for retrocompatibility reasons.

**Comment by evermeer** [comment]
A PR for that is definitely welcome!
Maybe it's possible to autodetect it it's a MRZ 2 or 3? If you have an OCR result where 3 lines have more than 30 characters, then it's probably a MRZ 3?

**Comment by punto2018** [comment]
This approach can be used, my only concern is in the performance in trying both parsers. 
It is not possible make simple assumptions in the number of lines. 
Italian ID Card for example have a barcode on top of MRZ and often the user also frame it, resulting in a 4 lines OCR result, where the first line is something like "I 1 III 1 || \ 1 .....".
In this case filtering the first line is an important improvement in MRZ scan. 
Anyway, I suggest a 3 value parsing type: auto, 2 lines, 3 lines, where auto can use a sort of "smart" choice in order to select the first parser to try. 

What do you think?

**Comment by Mattijah** [comment]
@evermeer, punto2018, sahar12345. Here is a MRZ parser with support of all oficial documents. On top of that it does some OCR cleaning too. https://github.com/Mattijah/QKMRZParser. All you need to do is just set it up as a pod. Enjoy

**Comment by evermeer** [comment]
The PR has been merged, pushed and published. There is now support for 3 line MRZ. Thanks @punto2018 !
