### ISSUE TITLE
iOS 10 compability

### ISSUE THREAD

**Issue by jrodriguezq** [evermeer/PassportScanner#6]
Since the release of iOS 10, PassportScanner no longer builds correctly.
Is there any know solution for this?

**Comment by evermeer** [comment]
The GPUImage2 branch is Swift 3, XCode 8, iOS 10.

But it has a bug. If you set a breakpoint on the first line of the doOCR function then you will see that the UIImage looks good but then the output of the ocr only returns data from the left half of the image.

**Comment by evermeer** [comment]
master is now also converted to swift3
The GPUImage2 branch is still work in progress...
