### ISSUE TITLE
EXC_BAD_ACCESS error at ImageConsumer.addSource

### ISSUE THREAD

**Issue by lunateck** [evermeer/PassportScanner#8]
Hi,

I am always hitting that error on EVGPUImage2, ImageConsumer.addSource and I've found not much help on this matter.

This happens when I click on the SCAN button in the demo project.

I am running the demo on ios 10.2 on a iPhone6+.
<img width="1011" alt="screen shot 2017-01-05 at 5 55 11 pm" src="https://cloud.githubusercontent.com/assets/4109828/21676332/3127d5c8-d370-11e6-9461-8a17c290b84e.png">

**Comment by evermeer** [comment]
My bad... This was caused by the latest rename of GPUImage2 to EVGPUImage2 (so that there could be full support for Cocoapods)

I just published a new version 2.0.2 that solves this issue.
