### ISSUE TITLE
Cocoapod error

### ISSUE THREAD

**Issue by Asich** [evermeer/PassportScanner#9]
Hi Edwin. I'm getting "Unable to find a specification for EVGPUImage2" error message after pod install, could you please help me?

My pod version is 1.2.0.beta.3

**Comment by evermeer** [comment]
Do you get that for the demo project? If you download or fork PassportScanner, then you should be able to run a `pod update`. I just did the same and I get:

```
MacBook-Pro:PassportScanner evermeer$ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using EVGPUImage2 (0.1.0)
Using GPUImage (0.1.7)
Using TesseractOCRiOS (4.0.0)
Using UIImage-Resize (1.0.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 4 total pods installed.
MacBook-Pro:PassportScanner evermeer$ 
```

**Comment by Asich** [comment]
Yes that definitely works,  instead of regular pod install command. Thanks, I appreciate your help!
